apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas | default "1" }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
        {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/pgbouncer-config-secret: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        checksum/pgbouncer-certificates-secret: {{ include (print $.Template.BasePath "/secret-certificates.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pgbouncer.serviceAccountName" . }}
      securityContext: 
        {{- toYaml .Values.securityContexts.pod | nindent 8 }}
      restartPolicy: Always
      {{- if or .Values.registry.secretName .Values.registry.connection }}
      imagePullSecrets:
        - name: {{ include "pgbouncer.registrySecret" . }}
      {{- end }}
      containers:
        - name: pgbouncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContexts.container | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: pgbouncer
              containerPort: {{ .Values.ports.pgbouncer }}
          {{- if or .Values.mountConfigSecret .Values.ssl.ca .Values.ssl.cert .Values.ssl.key .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.mountConfigSecret }}
            - name: pgbouncer-config
              subPath: pgbouncer.ini
              mountPath: /etc/pgbouncer/pgbouncer.ini
              readOnly: true
            - name: pgbouncer-config
              subPath: users.txt
              mountPath: /etc/pgbouncer/users.txt
              readOnly: true
            {{- end }}
            {{- if .Values.ssl.ca }}
            - name: pgbouncer-certificates
              subPath: ca.crt
              mountPath: /etc/pgbouncer/ca.crt
              readOnly: true
            {{- end }}
            {{- if .Values.ssl.cert }}
            - name: pgbouncer-certificates
              subPath: server.crt
              mountPath: /etc/pgbouncer/server.crt
              readOnly: true
            {{- end }}
            {{- if .Values.ssl.key }}
            - name: pgbouncer-certificates
              subPath: server.key
              mountPath: /etc/pgbouncer/server.key
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end}}
          {{- if .Values.containerLifecycleHooks }}
          lifecycle: {{- toYaml .Values.containerLifecycleHooks | nindent 12 }}
          {{- end }}
        {{- if .Values.metricsExporter.enabled }}
        - name: metrics-exporter
          resources: {{- toYaml .Values.metricsExporter.resources | nindent 12 }}
          image: "{{ .Values.metricsExporter.image.repository }}:{{ .Values.metricsExporter.image.tag }}"
          imagePullPolicy: {{ .Values.metricsExporter.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.metricsExporter.securityContexts.container | nindent 12 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgbouncer.statsSecret" . }}
                  {{- if (and .Values.metricsExporter.statsSecretName .Values.metricsExporter.statsSecretKey) }}
                  key: {{ .Values.metricsExporter.statsSecretKey }}
                  {{- else }}
                  key: "connection"
                  {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.pgbouncerScrape }}
          livenessProbe:
            exec:
              command:
                - pgbouncer_exporter
                - health
            initialDelaySeconds: {{ .Values.metricsExporter.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.metricsExporter.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.metricsExporter.livenessProbe.timeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - pgbouncer_exporter
                - health
            initialDelaySeconds: {{ .Values.metricsExporter.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.metricsExporter.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.metricsExporter.readinessProbe.timeoutSeconds }}
          {{- if .Values.metricsExporter.containerLifecycleHooks }}
          lifecycle: {{- toYaml .Values.metricsExporter.containerLifecycleHooks | nindent 12 }}
          {{- end }}
          {{- if .Values.metricsExporter.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.metricsExporter.extraVolumeMounts | nindent 12 }}
          {{- end}}
        {{- end }}
        {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
        {{- end }}
      {{- if or .Values.mountConfigSecret .Values.ssl.ca .Values.ssl.cert .Values.ssl.key .Values.extraVolumes }}
      volumes:
        {{- if .Values.mountConfigSecret }}
        - name: pgbouncer-config
          secret:
            secretName: {{ include "pgbouncer.configSecret" . }}
        {{- end}}
        {{- if or .Values.ssl.ca .Values.ssl.cert .Values.ssl.key }}
        - name: pgbouncer-certificates
          secret:
            secretName: {{ include "pgbouncer.certificatesSecret" . }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
