{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- with .Values.networkPolicy.ingress.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      ports:
        {{- with .Values.networkPolicy.ingress.ports }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
