{{- if and .Values.enabled (not .Values.configSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.configSecret" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: {{ include "pgbouncer.ini" . | b64enc }}
  users.txt: {{ include "pgbouncer.users" . | b64enc }}
type: Opaque
{{- end }}
