{{- if and .Values.enabled .Values.metricsExporter.enabled (not .Values.metricsExporter.statsSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.statsSecret" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  connection: {{ printf "postgresql://stats:stats@127.0.0.1:%v/pgbouncer?sslmode=%s" .Values.ports.pgbouncer .Values.metricsExporter.sslmode | b64enc }}
type: Opaque
{{- end }}
