{{- if and .Values.enabled (or .Values.ssl.ca .Values.ssl.cert .Values.ssl.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.certificatesSecret" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  {{- if .Values.ssl.ca }}
  ca.crt: {{ .Values.ssl.ca | b64enc }}
  {{- end }}
  {{- if .Values.ssl.cert }}
  server.crt: {{ .Values.ssl.cert | b64enc }}
  {{- end }}
  {{- if .Values.ssl.key }}
  server.key: {{ .Values.ssl.key | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
