apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metricsExporter.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.pgbouncerScrape | quote }}
    {{- end }}
    {{- if .Values.service.extraAnnotations }}
    {{- toYaml .Values.service.extraAnnotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}
  ports:
    - name: pgbouncer
      protocol: TCP
      port: {{ .Values.ports.pgbouncer }}
    {{- if .Values.metricsExporter.enabled }}
    - name: pgb-metrics
      protocol: TCP
      port: {{ .Values.ports.pgbouncerScrape }}
    {{- end }}
